#!/bin/bash
printf "%o" $(( $(echo $WATER|tr 'water' '01234'| tr -d '\n'|xargs -I{} printf "%d" "0{}") + $(echo $STIR|tr 'stir.' '01234'|tr -d '\n'|xargs -I{} printf "%d" "0{}") )) | tr '01234567' 'bestchol'
echo
